config/routes.rb
Rails.application.routes.draw do
  root 'extras#landing'

  get 'pages/error'

  get 'randoms/random'

  get 'offer', to: 'extras#offer'

  get 'loan', to: 'extras#loan'
  get 'loans', to: 'extras#loan'
  get 'contact_us', to: 'extras#contact_us'
  get 'savings', to: 'extras#savings'

  get 'account', to: 'pages#account'
  get 'account/:id', to: 'bank_accounts#show'
  get 'admin_panel', to: 'pages#admin_panel'

  post 'login', to: 'sessions#create_user'
  get 'login', to: 'sessions#new_user'
  match 'signup', to: 'pages#fakesignup', via: :get
  match 'signup_user', to: 'users#new', via: :get

  post 'admin/login', to: 'sessions#create_admin'
  get 'admin/login', to: 'sessions#new_admin'
  match 'admin/signup', to: 'admins#new', via: :get
  post 'admins', to: 'admins#create'

  delete 'logout', to: 'sessions#destroy'

  get 'admin_panel/users', to: 'users#index'

  resources :users do
    member do
      get :delete
    end
  end

  resources :bank_accounts do
    member do
      get :delete
      get :statement
      get :transfer
      get :payment
      post :transfer_money
      post :send_payment
    end
  end

  resources :bank_accounts do
    resources :transactions
  end

  # resources :currencies do
  #   member do
  #     get :delete
  #   end
  # end

  get 'admin', to: 'pages#admin'
  match "*path", to: 'pages#error404', via: :all

end

app/views/admins/_adminform.html.erb
<%= error_messages_for(f.object) %>
<dl class="form">
  <dt><%= f.label :username, "Username" %></dt>
  <dd><%= f.text_field(:username) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :email, "Email" %></dt>
  <dd><%= f.text_field(:email) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :email_confirmation, "Confirm Email" %></dt>
  <dd><%= f.text_field(:email_confirmation) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :password, "Password" %></dt>
  <dd><%= f.password_field(:password) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :password_confirmation, "Confirm Password" %></dt>
  <dd><%= f.password_field(:password_confirmation) %></dd>
</dl>

app/views/admins/delete.html.erb
<% @title="Delete Admin Account" %>
<div class="login-form-container clearfix">
  <h1>Delete Admins</h1>
  <%= link_to("View all admins", admins_path()) %>
  <%= form_for(@admin, :method => "delete") do |f| %>
    <p>Are you sure you want to delete this person?</p>
    <%= render(partial: 'adminform', locals: {f: f}) %>
    <%= f.submit('delete admin', :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/admins/edit.html.erb
<% @title="Edit Admin" %>
<div class="login-form-container clearfix">
  <h1>Edit Admin</h1>
  <%= link_to("View all admins", admins_path()) %>
  <%= form_for(@admin) do |f| %>
    <%= render(partial: 'adminform', locals: {f: f}) %>
    <%= f.submit("Update admin", :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/admins/index.html.erb
<% @title="All Admins" %>
<div class="container mt-5">
  <h1>View all Admins</h1>
  <%= link_to("Create new admin", new_admin_path()) %>
  <br/>
  <br/>
  <table class="table">
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= admin.email %></td>
        <td>
          <%= link_to('Show', admin_path(admin)) %>
          <%= link_to('Edit', edit_admin_path(admin)) %>
          <%= link_to('Delete', delete_admin_path(admin)) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admins/new.html.erb
<% @title="Admin Signup" %>
<div class="login-form login-form-container clearfix">
  <h1>Admin Account Creation</h1>
  <p>Create a new admin here</p>
  <%= form_for(@admin, :url => admins_path, :method => 'post') do |f| %>
    <%= render(partial: 'adminform', locals: {f: f}) %>
    <br/>
    <%= f.submit("Create admin", :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/admins/show.html.erb
<% @title="View Admin" %>
<div class="container mt-5">
  <h1>View Admin Details</h1>
  <p><%= link_to('Edit this admin', edit_admin_path(@admin)) %></p>
  <table class="table">
    <tr>
      <th>Username</th>
      <th>Email</th>
    </tr>
    <tr>
      <td><%= @admin.username %></td>
      <td><%= @admin.email %></td>
    </tr>
  </table>
</div>