config/routes.rb
Rails.application.routes.draw do
  root 'extras#landing'

  get 'pages/error'

  get 'randoms/random'

  get 'offer', to: 'extras#offer'

  get 'loan', to: 'extras#loan'
  get 'loans', to: 'extras#loan'
  get 'contact_us', to: 'extras#contact_us'
  get 'savings', to: 'extras#savings'

  get 'account', to: 'pages#account'
  get 'account/:id', to: 'bank_accounts#show'
  get 'admin_panel', to: 'pages#admin_panel'

  post 'login', to: 'sessions#create_user'
  get 'login', to: 'sessions#new_user'
  match 'signup', to: 'pages#fakesignup', via: :get
  match 'signup_user', to: 'users#new', via: :get

  post 'admin/login', to: 'sessions#create_admin'
  get 'admin/login', to: 'sessions#new_admin'
  match 'admin/signup', to: 'admins#new', via: :get
  post 'admins', to: 'admins#create'

  delete 'logout', to: 'sessions#destroy'

  get 'admin_panel/users', to: 'users#index'

  resources :users do
    member do
      get :delete
    end
  end

  resources :bank_accounts do
    member do
      get :delete
      get :statement
      get :transfer
      get :payment
      post :transfer_money
      post :send_payment
    end
  end

  resources :bank_accounts do
    resources :transactions
  end

  # resources :currencies do
  #   member do
  #     get :delete
  #   end
  # end

  get 'admin', to: 'pages#admin'
  match "*path", to: 'pages#error404', via: :all

end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :admin
    has_many :bank_accounts
    has_one :currency 
    has_secure_password
    validates :password, length: { minimum: 6 }
    validates :first_name, presence: true, length: {minimum: 2}
    validates :last_name, presence: true, length: {minimum: 2}
    validates :email, presence: true, confirmation: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :email_confirmation, presence: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destory
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in_as_admin
  before_action :redirect_to_index_if_not_current_admins_user, only: [:show, :edit, :update, :delete, :destroy]

  # Gets all users belonging to the current user/admin and orders them by id
  def index
    @users = User.where(admin: current_user)
  end

  # Shows a particular user by the given id
  def show
    @user = User.find(params[:id])
  end

  # For the page to create a new user
  def new
    @user = User.new
  end

  # Where the post request to actually validate and create the user is processed
  def create
    @admin = current_user
    @user = User.new(user_params)
    @user.admin = @admin
    if @user.valid? && @user.save
      redirect_to(users_path)
    else
      render('new')
    end
  end

  # Finds the user by id to be edited
  def edit
    @user = User.find(params[:id])
  end

  # Similar to create. Updates the user based on the params in the form.
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(user_path(@user))
    else
      render('edit')
    end
  end

  # Finds the user for the delete user page
  def delete
    @user = User.find(params[:id])
  end

  # Actually deletes/destroys the user by id and redirects back to the users index
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_path)
  end

  private
    # Checks that the params given are permitted
    def user_params
      params.require(:user).permit(:first_name, :middle_name, :last_name, :email, :email_confirmation, :password, :password_confirmation, :currency_id)
    end

    # Ensures user cannot view the users if you're not logged in as an admin
    def redirect_to_root_if_not_logged_in_as_admin
      unless logged_in? && is_admin?
        redirect_to(root_path)
      end
    end

    # Ensures user cannot view a user if it doesn't belong to the current admin
    def redirect_to_index_if_not_current_admins_user
      @user = User.find(params[:id])
      unless @user.admin == current_user
        redirect_to(users_path)
      end
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<p>First Name</p>
<%= f.text_field(:first_name) %>

<p>Middle Name</p>
<%= f.text_field(:middle_name) %>

<p>Last Name</p>
<%= f.text_field(:last_name) %>

<p>Email</p>
<%= f.text_field(:email) %>

<p>Confirm email</p>
<%= f.text_field(:email_confirmation) %>

<p>Password</p>
<%= f.text_field(:password) %>

<p>Confirm password</p>
<%= f.text_field(:password_confirmation) %>

app/views/users/_userform.html.erb
<%= error_messages_for(f.object) %>
<dl class="form">
  <dt><%= f.label :first_name, "First Name" %></dt>
  <dd><%= f.text_field(:first_name) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :middle_name, "Middle Name" %></dt>
  <dd><%= f.text_field(:middle_name) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :last_name, "Last Name" %></dt>
  <dd><%= f.text_field(:last_name) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :email, "Email" %></dt>
  <dd><%= f.text_field(:email) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :email_confirmation, "Confirm email" %></dt>
  <dd><%= f.text_field(:email_confirmation) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :password, "Password" %></dt>
  <dd><%= f.password_field(:password) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :password_confirmation, "Confirm password" %></dt>
  <dd><%= f.password_field(:password_confirmation) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :currency_id, "Currency" %></dt>
  <% if Currency.count != 0 %>
  <dd><%= f.collection_select(:currency_id, Currency.all, :id, :code) %></dd>
  <% else %>
  <%
  Currency.create!(code:"USD", symbol:"$", rate_to_gbp:0.75)
  Currency.create!(code:"GBP", symbol:"£", rate_to_gbp:1)
  Currency.create!(code:"CNY", symbol:"¥", rate_to_gbp:0.11)
  Currency.create!(code:"EUR", symbol:"€", rate_to_gbp:0.90)
  Currency.create!(code:"DKK", symbol:"Kr.", rate_to_gbp:0.12)
  Currency.create!(code:"MYR", symbol:"RM", rate_to_gbp:0.18)
  %>
  <dd><%= f.collection_select(:currency_id, Currency.all, :id, :code) %></dd>
  <% end %>
</dl>

app/views/users/delete.html.erb
<% @title="Delete User" %>

<h1>Delete this user</h1>
<p>You can delete your users from this page. All their information will be deleted too.</p>
<%= link_to("View all users", users_path()) %>
<%= link_to('Edit this user', edit_user_path(@user)) %>
<%= form_for(@user, :method => "delete") do |f| %>
  <p>Are you sure you want to delete this person?</p>
  <%= render(partial: 'userform', locals: {f: f}) %>
  <%= f.submit('delete user') %>
<% end %>

app/views/users/edit.html.erb
<% @title="Edit User" %>
<div class="login-form-container clearfix">
  <h1>Edit your user</h1>
  <p>You can edit any of your users details here, but they must still be valid.</p>
  <%= link_to("View all users", users_path()) %>
  <%= form_for(@user) do |f| %>
    <%= render(partial: 'userform', locals: {f: f}) %>
    <%= f.submit("Update User", :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/users/index.html.erb
<% @title="View All Users" %>
<div class="container mt-5">
  <h1>All your users!</h1>
  <p>View all your users and make modifications to them by clicking the buttons to the right.</p>
  <%= link_to("Create new user", new_user_path()) %> | 
  <%= link_to('Create Bank Account', new_bank_account_path()) %>
  <br/><br/>
  <table class="table">
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Currency</th>
      <th>Number of Bank Account</th>
      <th>Actions</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.middle_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= Currency.find(user.currency_id).code %></td>
        <td><%= user.bank_accounts.count %></td>
        <td>
          <%= link_to('Show', user_path(user)) %> |
          <%= link_to('Edit', edit_user_path(user)) %> |
          <%= link_to('Delete', delete_user_path(user)) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% @title="Create New User" %>
<div class="login-form login-form-container clearfix">
  <h1>Create a new user</h1>
  <%= link_to("View all users", users_path()) %>
  <%= form_for(@user, :url => users_path, :method => 'post') do |f| %>
    <%= render(partial: 'userform', locals: {f: f}) %>
    <%= f.submit("Create User", :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/users/show.html.erb
<% @title="View User" %>
<div class="container mt-5">
  <h1>View your user</h1>
  <%= link_to("View all users", users_path()) %>
  <br/>
  <%= link_to('Edit this user', edit_user_path(@user)) %>
  <br/>
  <br/>
  <table class="table">
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Password</th>
    </tr>
    <tr>
      <td><%= @user.first_name %></td>
      <td><%= @user.middle_name %></td>
      <td><%= @user.last_name %></td>
      <td><%= @user.email %></td>
      <td><%= @user.password %></td>
    </tr>
  </table>
</div>