config/routes.rb
Rails.application.routes.draw do
  root 'extras#landing'

  get 'pages/error'

  get 'randoms/random'

  get 'offer', to: 'extras#offer'

  get 'loan', to: 'extras#loan'
  get 'loans', to: 'extras#loan'
  get 'contact_us', to: 'extras#contact_us'
  get 'savings', to: 'extras#savings'

  get 'account', to: 'pages#account'
  get 'account/:id', to: 'bank_accounts#show'
  get 'admin_panel', to: 'pages#admin_panel'

  post 'login', to: 'sessions#create_user'
  get 'login', to: 'sessions#new_user'
  match 'signup', to: 'pages#fakesignup', via: :get
  match 'signup_user', to: 'users#new', via: :get

  post 'admin/login', to: 'sessions#create_admin'
  get 'admin/login', to: 'sessions#new_admin'
  match 'admin/signup', to: 'admins#new', via: :get
  post 'admins', to: 'admins#create'

  delete 'logout', to: 'sessions#destroy'

  get 'admin_panel/users', to: 'users#index'

  resources :users do
    member do
      get :delete
    end
  end

  resources :bank_accounts do
    member do
      get :delete
      get :statement
      get :transfer
      get :payment
      post :transfer_money
      post :send_payment
    end
  end

  resources :bank_accounts do
    resources :transactions
  end

  # resources :currencies do
  #   member do
  #     get :delete
  #   end
  # end

  get 'admin', to: 'pages#admin'
  match "*path", to: 'pages#error404', via: :all

end

app/views/pages/account.html.erb
<% @user = current_user %>
<% currency = Currency.find(current_user[:currency_id]) %>
<% @title="King's Banking | #{@user[:first_name].to_s} #{@user[:last_name].to_s}" %>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Your KB Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div style="margin: 10px; margin-bottom: 300px">
      <!-- Welcome text to the account with your name and maybe some options to other pages -->
      <div>
        <h1>Welcome <%= @user[:first_name] + " " + @user[:last_name] %></h1>
        <h6><kbd>Last logged in: <%= @user[:last_logged_in] %></kbd></h6>
      </div>
      <!-- side panel about messages / special offers to the left -->
      <div class="card" style="margin: 2%">
        <div class="card-header">
          Tip of the day!
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>Don't let unknown callers access your bank account! Be wary of those who call claiming to offer a refund, tech support for viruses or other malicious scams!</p>
            <footer class="blockquote-footer">Jim Browning<cite title="Source Title">, YouTube</cite></footer>
          </blockquote>
        </div>
      </div>
      <div class="container-xl">
        <div class="row">
          <div class="col-sm-3">
            <div class="card text-center" style="width: 100%">
              <div class="card-header bg-danger font-weight-bold">
                Featured Offers
              </div>
              <div class="card-body">
                <h5 class="card-title">10% Cashback on selected stores!</h5>
                <div class="card-body">
                  <%= image_tag("amazon.png", :alt => "Amazon Logo", height: '32') %>
                  <%= image_tag("apple.png", :alt => "Apple Logo", height: '32') %>
                  <%= image_tag("dell.png", :alt => "Dell Logo", height: '32') %>
                </div>
                <a href="/offer" class="btn btn-primary">View all offers</a>
              </div>
              <div class="card-footer text-dark bg-danger">
                Offer expires in 2 days
              </div>
            </div>
          </div>
          <!-- list of your accounts, their current balance and some other information with buttons for view statements, make payment, make transfer and more actions -->
          <div class="col-sm-9">
            <div class="container">
              <% BankAccount.where(user: @user).each do |account| %>
                <% transactions = Transaction.where(bank_account: account) %>
                <% money_in = transactions.calculate(:sum, :money_in) %>
                <% money_out = transactions.calculate(:sum, :money_out) %>
                <div class="card" style="width: 80%">
                  <div class="card-body">
                    <h4 class="card-title"><%= account[:account_name] %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><kbd>Account Number: <%= account[:account_number] %> | Sort Code: <%= account[:sort_code] %></kbd></h6>
                    <h5 class="card-text">Current balance: <b><%= number_to_currency((money_in - money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></b> | Interest rate: <%= account[:interest_rate] %>%</p>
                    <%= link_to "View Statement", statement_bank_account_path(account) %> |
                    <%= link_to "Transfer Between Accounts", transfer_bank_account_path(account) %> |
                    <%= link_to "Make Payment", payment_bank_account_path(account) %>
                  </div>
                </div>
                <br/>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/admin_panel.html.erb
<% @title="King's Banking | Admin Panel" %>
<br/>
<div class="container">
  <!-- Content here -->
  <div class="jumbotron bg-secondary text-white">
    <h2 class="display-4">Hello, Administrator <%= current_user[:username] %>.</h2>
    <p class="lead">Start managing users, accounts and transaction histories from below.</p>
  </div>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <div class="col">
      <div class="card h-100 text-dark bg-white">
        <div class="card-body">
          <h3 class="card-title"><%=link_to 'Generate Random Data', randoms_random_path, :class => "btn btn-primary" %></h3>
          <p class="card-text">Generate random users, bank accounts and corresponding transactions all in once.</p>
        </div>
        <%= image_tag("adminImages/random.jpg", class:"card-img-top") %>
      </div>
    </div>
    <div class="col">
      <div class="card h-100 text-dark bg-white">
        <div class="card-body">
          <h3 class="card-title"><%=link_to 'Manage Users', users_path %></h3>
          <p class="card-text">Create / view / edit / delete bank users.</p>
          <%=link_to 'Create a new user', signup_user_path, :class => "btn btn-primary" %>
        </div>
        <%= image_tag("adminImages/user.jpg", class:"card-img-top") %>
      </div>
    </div>
    <div class="col">
      <div class="card h-100 text-dark bg-white">
        <div class="card-body">
          <h3 class="card-title"><%=link_to 'Manage Bank Accounts & Transactions', bank_accounts_path %></h3>
          <p class="card-text">Manually create / view / edit / delete bank accounts and corresponding transaction histories.</p>
          <%=link_to 'Create a new bank account', new_bank_account_path, :class => "btn btn-primary" %>
      </div>
      <%= image_tag("adminImages/account.jpg", class:"card-img-top") %>
    </div>
  </div>
  <div class="col">
    <div class="card h-100 text-dark bg-white">
      <div class="card-body">
        <h3 class="card-title">Useful Links</h3>
        <p class="card-text"><%=link_to 'View all users', users_path() %></p>
        <p class="card-text"><%=link_to 'View all bank accounts and corresponding transactions', bank_accounts_path() %></p>
      </div>
      <%= image_tag("adminImages/link.jpg", class:"card-img-top") %>
    </div>
  </div>
</div>
</div>

app/views/pages/adminlogin.html.erb
<!---Diaplay login form.--->

<div class="login-form-container clearfix">
  <%= image_tag("logos/logo1.png",width:"200") %>
  <h5>Please log into ADMIN pannel</h5>
  <br>
  <div class="login-form">
    <%= form_with scope: :page, url: pages_admin_login_path, local:true do |f| %>
    <dl class="form">
      <dt><%= f.label :name, "Username:" %></dt>
      <dd><%= f.text_field :name %></dd>
    </dl>

    <dl class="form">
      <dt><%= f.label :password, "Password:" %></dt>
      <dd><%= f.password_field :password %></dd>
    </dl>

    <p><%= f.submit "Log In", :class => "login-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/pages/error.html.erb
<br></br>
<div class="container">
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Alert!</h4>
    <p>Invalid username or password.</p>
    <p>Please try again.</p>
    <hr>
  </div>
</div>

app/views/pages/error404.html.erb
<br></br>
<div class="container">
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">The request you're trying to make is not valid</h4>
    <p>Check the URL you're on is correct.</p>
    <p>Contact the bank if you think the problem is on our end!</p>
    <hr>
  </div>
</div>

app/views/pages/fakesignup.html.erb
<% @title="Join King's Banking" %>
<div class="login-form login-form-container clearfix">
  <h2>Join King's Banking</h2>
  <div class="container">
    <%= image_tag("logos/logo.png", width:"200") %>
  </div>
  <p>After filling in this form, you will be emailed for additional information. We look forward to you joining us!</p>
  <dl class="form">
    <dt><label for="post_title">First Name</label></dt>
    <dd><input type="text" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Middle Name</label></dt>
    <dd><input type="text" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Last Name</label></dt>
    <dd><input type="text" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Email</label></dt>
    <dd><input type="text" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Email Confirmation</label></dt>
    <dd><input type="text" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Password</label></dt>
    <dd><input type="password" id="fname" name="fname"></dd>
  </dl>
  <dl class="form">
    <dt><label for="post_title">Password Confirmation</label></dt>
    <dd><input type="password" id="fname" name="fname"></dd>
  </dl>
  <button class="login-button btn btn-primary">Continue</button>
  <br/>
  <br/>
  <p>Please contact King's Banking for any issues.</p>
</div>

app/views/pages/homepage.html.erb
<!---Diaplay login form.--->

<div class="login-form-container clearfix">
  <%= image_tag("logos/logo1.png",width:"200") %>
  <h5>Please log in.</h5>
  <br>
  <div class="login-form">
    <%= form_with scope: :page, url: pages_user_login_path, local:true do |f| %>
    <dl class="form">
      <dt><%= f.label :email, "Email:" %></dt>
      <dd><%= f.text_field :email %></dd>
    </dl>

    <dl class="form">
      <dt><%= f.label :password, "Password:" %></dt>
      <dd><%= f.password_field :password %></dd>
    </dl>


    <p><%= f.submit "Log In", :class => "login-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>