config/routes.rb
Rails.application.routes.draw do
  root 'extras#landing'

  get 'pages/error'

  get 'randoms/random'

  get 'offer', to: 'extras#offer'

  get 'loan', to: 'extras#loan'
  get 'loans', to: 'extras#loan'
  get 'contact_us', to: 'extras#contact_us'
  get 'savings', to: 'extras#savings'

  get 'account', to: 'pages#account'
  get 'account/:id', to: 'bank_accounts#show'
  get 'admin_panel', to: 'pages#admin_panel'

  post 'login', to: 'sessions#create_user'
  get 'login', to: 'sessions#new_user'
  match 'signup', to: 'pages#fakesignup', via: :get
  match 'signup_user', to: 'users#new', via: :get

  post 'admin/login', to: 'sessions#create_admin'
  get 'admin/login', to: 'sessions#new_admin'
  match 'admin/signup', to: 'admins#new', via: :get
  post 'admins', to: 'admins#create'

  delete 'logout', to: 'sessions#destroy'

  get 'admin_panel/users', to: 'users#index'

  resources :users do
    member do
      get :delete
    end
  end

  resources :bank_accounts do
    member do
      get :delete
      get :statement
      get :transfer
      get :payment
      post :transfer_money
      post :send_payment
    end
  end

  resources :bank_accounts do
    resources :transactions
  end

  # resources :currencies do
  #   member do
  #     get :delete
  #   end
  # end

  get 'admin', to: 'pages#admin'
  match "*path", to: 'pages#error404', via: :all

end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :user
    has_many :transactions, dependent: :destroy
    validates :account_name, presence: true
    validates :account_number, presence: true, length: { is: 16 },uniqueness: true
    validates :sort_code, presence: true, length: { is: 6 },uniqueness: true
    validates :interest_rate, presence: true
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  
  # Get bank accounts according to user's id
  def index
    @users = User.where(admin: current_user)
    @bank_accounts = BankAccount.where(user: @users)
  end

  def new
    @users = User.where(admin: current_user)
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new(account_name: params[:bank_account][:account_name], account_number: params[:bank_account][:account_number], sort_code: params[:bank_account][:sort_code], interest_rate: params[:bank_account][:interest_rate])
    @bank_account.user = User.find(params[:bank_account][:user_id])
    if @bank_account.valid? && @bank_account.save
      redirect_to(bank_accounts_path)
    else
      render('new')
    end
  end

  def update
    respond_to do |format|
      if @bank_account.update(account_name: params[:bank_account][:account_name], account_number: params[:bank_account][:account_number], sort_code: params[:bank_account][:sort_code], interest_rate: params[:bank_account][:interest_rate])
        format.html { redirect_to bank_accounts_path(@bank_account), notice: 'Bank account was successfully updated.' }
      else
        format.html { render :edit, notice: 'Error! Bank account can not be updated.' }
      end
    end
  end

  def destroy
    @bank_account.destroy
    respond_to do |format|
     format.html { redirect_to bank_accounts_path(@bank_account), notice: 'Bank account was successfully destroyed.' }
   end
  end
  
  def statement
    @bank_account = BankAccount.find(params[:id])
  end

  def transfer
    @user_bank_accounts = BankAccount.where(user: current_user)
    @bank_account = BankAccount.find(params[:id])
  end

  def transfer_money
    currency = Currency.find(current_user[:currency_id])
    @from_bank_account = BankAccount.find(params[:id])
    @to_bank_account = BankAccount.find(params[:bank_account_id])
    @description = "TRANSFER FROM " + [current_user[:first_name], current_user[:last_name], @from_bank_account[:account_name]].map(&:to_s).join(', ')
    @reference = "TRANSFER FROM " + [current_user[:first_name], current_user[:last_name], @from_bank_account[:account_name]].map(&:to_s).join(', ')
    @amount = params[:amount].to_f * currency[:rate_to_gbp]
    @time = Time.now

    @out = Transaction.new(bank_account: @from_bank_account, date: @time, description: @description, reference: @reference, money_in: 0, money_out: @amount)
    @in = Transaction.new(bank_account: @to_bank_account, date: @time, description: @description, reference: @reference, money_in: @amount, money_out: 0)

    if @out.valid? && @in.valid? && @out.save && @in.save
      redirect_to statement_bank_account_path(@from_bank_account)
    else
      redirect_to transfer_bank_account_path(@from_bank_account)
    end
  end

  def payment
    @bank_account = BankAccount.find(params[:id])
  end

  def send_payment
    currency = Currency.find(current_user[:currency_id])
    @from_bank_account = BankAccount.find(params[:id])
    @to_account_number = params[:account_number]
    @to_sort_code = params[:sort_code]
    @description = params[:description]
    @reference = params[:reference]
    @amount = params[:amount].to_f * currency[:rate_to_gbp]
    @time = Time.now

    @out = Transaction.new(bank_account: @from_bank_account, date: @time, description: @description, reference: @reference, money_in: 0, money_out: @amount)

    if @out.valid? && @out.save
      redirect_to statement_bank_account_path(@from_bank_account)
    else
      redirect_to transfer_bank_account_path(@from_bank_account)
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bank_account
    @bank_account = BankAccount.find(params[:id])
  end
end

app/views/bank_accounts/_bank_accountform.html.erb
<%= error_messages_for(f.object) %>
<dl class="form">
  <dt><%= f.label :account_name, "Account Name" %></dt>
  <dd><%= f.text_field(:account_name) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :account_number, "Account Number" %></dt>
  <dd><%= f.text_field(:account_number) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :sort_code, "Sort Code" %></dt>
  <dd><%= f.text_field(:sort_code) %></dd>
</dl>
<dl class="form">
  <dt><%= f.label :interest_rate, "Interest Rate" %></dt>
  <dd><%= f.number_field(:interest_rate, step: :any) %></dd>
</dl>

app/views/bank_accounts/edit.html.erb
<% @title="Edit Bank Account" %>
<div class="login-form-container clearfix">
  <h1>Edit Bank Account</h1>
  <%= link_to("View all bank accounts", bank_accounts_path()) %>
  <%= form_for(@bank_account) do |f| %>
    <%= render(partial: 'bank_accountform', locals: {f: f}) %>
    <%= f.submit("Update Bank Account", :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/bank_accounts/index.html.erb
<% @title="View Bank Accounts" %>
<div class="container mt-5">
  <h1>View all your bank accounts.</h1>
  <p>View all your Bank Accounts and initiate actions to them by clicking the buttons to the right.</p>
  <%= link_to("Create new bank account", new_bank_account_path()) %>
  <br>
</br>
<table class="table">
  <tr>
    <th>Owner</th>
    <th>Account Name</th>
    <th>Account Number</th>
    <th>Sort Code</th>
    <th>Interest rate</th>
    <th>Actions</th>
  </tr>
  <% @bank_accounts.each do |bank_account| %>
    <tr>
      <td><%= bank_account.user.first_name %> <%= bank_account.user.middle_name %> <%= bank_account.user.last_name %></td>
      <td><%= bank_account.account_name %></td>
      <td><%= bank_account.account_number %></td>
      <td><%= bank_account.sort_code %></td>
      <td><%= bank_account.interest_rate %></td>
      <td>
        <%= link_to 'Edit', edit_bank_account_path(bank_account) %> |
        <%= link_to 'Destroy',bank_account, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <%= link_to 'Create Transactions', new_bank_account_transaction_path(bank_account)%> |
        <%= link_to 'View Transactions', bank_account_transactions_path(bank_account) %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/bank_accounts/new.html.erb
<% @title="Create Bank Account" %>
<div class="login-form login-form-container clearfix">
  <h1>Create a new Bank Account for a user</h1>
  <%= link_to("View all bank accounts", bank_accounts_path()) %>
  <%= form_for(@bank_account, :url => bank_accounts_path, :method => 'post') do |f| %>
    <dt>Which user is this account for?</dt>
    <%= f.collection_select(:user_id, @users, :id, :first_name, {prompt: "Please select user"}) %>
    <%= render(partial: 'bank_accountform', locals: {f: f}) %>
  <%= f.submit("Create Bank Account", :class => "login-button btn btn-primary") %>
<% end %>
</div>

app/views/bank_accounts/payment.html.erb
<% @title="Make Payment" %>
<% currency = Currency.find(current_user[:currency_id]) %>
<% transactions = Transaction.where(bank_account: @bank_account) %>
<% money_in = transactions.calculate(:sum, :money_in) %>
<% money_out = transactions.calculate(:sum, :money_out) %>
<div class="login-form login-form-container">
  <h1>Make a payment from <%= @bank_account[:account_name] %></h1>
  <h2>Account number: <%= @bank_account[:account_number] %></h2>
  <h2>Sort code: <%= @bank_account[:sort_code] %></h2>
  <h3>Balance: <%= number_to_currency((money_in - money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></h3>
  <%= link_to("Return to view all accounts", '/account') %>
  <%= form_with(model: @transaction, url: 'send_payment', local: true) do |f| %>
    <%= error_messages_for(f.object) %>
    <p>This payment will be from the following account: <%= @bank_account[:account_name] %></p>
    <dt>To (account number)</dt>
    <%= f.text_field(:account_number) %>
    <dt>To (sort code)</dt>
    <%= f.text_field(:sort_code) %>
    <dt>Amount</dt>
    <%= f.text_field(:amount) %>
    <dt>Description / Purpose</dt>
    <%= f.text_field(:description) %>
    <dt>Reference</dt>
    <%= f.text_field(:reference) %>
    <br>
    <br>
    <%= f.submit("Send payment", data: { confirm: 'Are you sure?' }, :class => "login-button btn btn-primary") %>
  <% end %>
</div>

app/views/bank_accounts/show.html.erb
<% @title="View Bank Account Transactions" %>
<% currency = Currency.find(current_user[:currency_id]) %>
<% transactions = Transaction.where(bank_account: @bank_account) %>
<% money_in = transactions.calculate(:sum, :money_in) %>
<% money_out = transactions.calculate(:sum, :money_out) %>
<div class="container mt-5">
  <h1>Statement for <%= @bank_account[:account_name] %></h1>
  <h2>Account number: <%= @bank_account[:account_number] %> | Sort code: <%= @bank_account[:sort_code] %></h2>
  <h3>Balance: <%= number_to_currency((money_in - money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %> | Interest rate: <%= @bank_account[:interest_rate] %>%</h3>
  <table class="table table-striped table-bordered">
    <thead class="thead-light">
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Reference</th>
        <th>Money In</th>
        <th>Money Out</th>
      </tr>
    </thead>
    <% transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.reference %></td>
        <td><%= number_to_currency((transaction.money_in) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
        <td><%= number_to_currency((transaction.money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td>Totals:</td>
      <td><%= number_to_currency((money_in) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
      <td><%= number_to_currency((money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
    </tr>
  </table>
</div>

app/views/bank_accounts/statement.html.erb
<% @title="View Bank Statement" %>
<% currency = Currency.find(current_user[:currency_id]) %>
<% transactions = Transaction.where(bank_account: @bank_account).order(:date).reverse_order %>
<% money_in = transactions.calculate(:sum, :money_in) %>
<% money_out = transactions.calculate(:sum, :money_out) %>
<div class="container mt-5">
  <h1>Statement for <%= @bank_account[:account_name] %></h1>
  <h2>Account number: <%= @bank_account[:account_number] %> | Sort code: <%= @bank_account[:sort_code] %></h2>
  <h3>Balance: <%= number_to_currency((money_in - money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %> | Interest rate: <%= @bank_account[:interest_rate] %>%</h3>
  <%= link_to("Return to view all accounts", '/account') %>
  <table class="table table-striped table-bordered">
    <thead class="thead-light">
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Reference</th>
        <th>Money In</th>
        <th>Money Out</th>
      </tr>
    </thead>
    <% transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.reference %></td>
        <td><%= number_to_currency((transaction.money_in) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
        <td><%= number_to_currency((transaction.money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td>Totals:</td>
      <td><%= number_to_currency((money_in) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
      <td><%= number_to_currency((money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></td>
    </tr>
  </table>
</div>

app/views/bank_accounts/transfer.html.erb
<% @title="Make Bank Transfer" %>
<% currency = Currency.find(current_user[:currency_id]) %>
<% transactions = Transaction.where(bank_account: @bank_account) %>
<% money_in = transactions.calculate(:sum, :money_in) %>
<% money_out = transactions.calculate(:sum, :money_out) %>
<h1>Transfer money from <%= @bank_account[:account_name] %> to another account</h1>
<div class="login-form login-form-container">
  <h2>Account number: <%= @bank_account[:account_number] %></h2>
  <h2>Sort code: <%= @bank_account[:sort_code] %></h2>
  <h3>Balance: <%= number_to_currency((money_in - money_out) / currency[:rate_to_gbp], :unit => currency[:symbol]) %></h3>
  <%= link_to("Return to view all accounts", '/account') %>
  <%= form_with(model: @transaction, url: 'transfer_money' ,local: true) do |f| %>
    <%= error_messages_for(f.object) %>
    <p>This transfer will be from the following account: <%= @bank_account[:account_name] %></p>
    <dt>To</dt>
    <%= f.collection_select(:bank_account_id, @user_bank_accounts, :id, :account_name, {prompt: "Please select bank account"}) %>
    <br/>
    <br/>
    <dt>Amount</dt>
    <%= f.text_field(:amount) %>
    <br>
    <br>
    <%= f.submit("Transfer money", data: { confirm: 'Are you sure?' }, :class => "login-button btn btn-primary") %>
  <% end %>
</div>